spring:
  application:
    name: kafka_tutorial

  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9094
    # Consumer configuration
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
          spring.json.trusted.packages: com.donext.kafka_tutorial.model
    # Producer configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer